# This is a test config for prototyping the sonic relayer

root_dir = ".sonic"
moniker = "sonic"
# this is used to sign cosmos sdk txs
# address: cosmos154ze66ytxnlmekg88cr3mnlz25s6lhe6sctthy
mnemonic = "blade chair elder arena flip lend primary clever vacuum clinic enlist tent alarm fiscal surface impose squirrel dinosaur cargo enter nation total clinic train"
max_peers = 5

[chain_a]

name = "chain-a"
id = "test-1"
listen_address = "0.0.0.0:9001"
external_address = "0.0.0.0:9001"
rpc = "http://127.0.0.1:16657"
peers = "e5601c8f9ca6f6d9c6be2bc84a1c97c163849932@127.0.0.1:16656"
app_version = 0
revision_number = 0
client_id = "client-0"
connection_id = "connection-0"
channel_id = "channel-0"
port_id = "transfer"
channel_version = "ics20-1"

[chain_b]

name = "chain-b"
id = "test-2"
listen_address = "0.0.0.0:9002"
external_address = "0.0.0.0:9002"
rpc = "http://127.0.0.1:26657"
peers = "98bc68d62f5372477174fb13b49f6f98b7c4f9c4@127.0.0.1:26656"
app_version = 0
revision_number = 0
client_id = "client-0"
connection_id = "connection-0"
channel_id = "channel-0"
port_id = "transfer"
channel_version = "ics20-1"