// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	tenderminttypes "github.com/tendermint/tendermint/types"

	types "github.com/tendermint/tendermint/proto/tendermint/types"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Commit provides a mock function with given fields: blockID, commit, valSet
func (_m *Handler) Commit(blockID []byte, commit *types.SignedHeader, valSet *types.ValidatorSet) {
	_m.Called(blockID, commit, valSet)
}

// Process provides a mock function with given fields: block
func (_m *Handler) Process(block *tenderminttypes.Block) error {
	ret := _m.Called(block)

	var r0 error
	if rf, ok := ret.Get(0).(func(*tenderminttypes.Block) error); ok {
		r0 = rf(block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
